import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import {
  ConnectButton,
  midnightTheme,
  darkTheme,
} from "@rainbow-me/rainbowkit";
import { abi, RESEARCH_CONTRACT_ADDRESS } from "../constants";
import { Contract, providers, utils } from "ethers";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Login Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Martel+Sans&display=swap" rel="stylesheet"></link>
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div className={`${styles.splitLeft} ${styles.left}  border-blue-500 flex justify-center relative`}>
            <div className=" self-center relative border-red-500 h-[100%] flex">
              <Image
                className=" self-center"
                height={1002}
                width={700}
                style={{objectFit:"cover", }}
                src="/textimg.webp"
              ></Image>
            </div>
          </div>
          <div className={`${styles.splitRight} ${styles.right}`}>
            <div className={styles.centered}>
              <div className={`${styles.loginCard} border-2`}>
                
                  <h2 className={`${styles.heading} border-2`}>Welcome !</h2>
                  <input
                    className={`${styles.inputField} border-2 border-red-500`}
                    type="text"
                    placeholder="Username"
                  />
                  <br></br>
                  <button className={styles.buttonEl1}>Add here</button>
                  <br></br>
                  <button className={styles.buttonEl2}>Create Account</button>
                <Image className={styles.vector} src="/undrawPic.png" width={400} height={300}></Image>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
