import mockData from "./mockData";
import Head from "next/head";
import Image from "next/image";
import ResearchCard from "./components/ResearchCard";
import researchDataLog from "./data/researchDataLog";
import React from "react";
import LibraryCard from "./components/LibraryCard.js"
import {
  ConnectButton,
  midnightTheme,
  darkTheme,
} from "@rainbow-me/rainbowkit";
import { abi, RESEARCH_CONTRACT_ADDRESS } from "../constants";
import { Contract, providers, utils } from "ethers";
import Link from "next/link";

export default function UserProfile() {
  const content = mockData.map((item) => {
    return <LibraryCard key={item.id} {...item} />;
  });
  return (
    <>
      <Head>
        <title>Login Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="rese">
        <div className="cards-grids">
            {content}
        </div>
      </main>
      </>
  )
}