import Head from "next/head";
import Image from "next/image";
import ResearchCard from "./components/ResearchCard";
import researchDataLog from "./data/researchDataLog";
import React from "react";
import {
  ConnectButton,
  midnightTheme,
  darkTheme,
} from "@rainbow-me/rainbowkit";
import { abi, RESEARCH_CONTRACT_ADDRESS } from "../constants";
import { Contract, providers, utils } from "ethers";
import Link from "next/link";

export default function Research() {
  const content = researchDataLog.map((item) => {
    return <ResearchCard key={item.id} {...item} />;
  });
  return (
    <>
      <Head>
        <title>Login Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="rese">
       <div className="nav-com  border-red-500 h-8 flex">
       <Link href="./">
          <h2 className=" mt-4 ml-4 header-el font-Michroma  self-center text-gray-100 border-blue-500 h-min">
            SCHOLAR3
          </h2>
        </Link>
        </div>
      
        <div className=" text-center">
          <h2 className="lib-el font-Inconsolata tracking-wide text-[#6862e3] text-[2.5em] font-black">
            Browse all Research Papers
          </h2>
        </div>
        <div className="cards-grids">{content}</div>
      </main>
    </>
  );
}
