
import styles from "../../styles/Home.module.css";
import Link from "next/link";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import { RESEARCH_CONTRACT_ADDRESS, researchAbi } from "../../constants";
import { Contract, providers, utils, BigNumber } from "ethers";
import {
  useAccount,
  useProvider,
  useContractRead,
  useConnect,
  usePrepareContractWrite,
  useContractWrite,
  useContractEvent
} from "wagmi";
import { useEffect, useState } from "react";
import { mantle } from "../_app";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {

const [name, setName] = useState("")
function nameChange(event){
  setName(event.target.value)
}

const newResearcherconfig = usePrepareContractWrite({
  address: RESEARCH_CONTRACT_ADDRESS,
  abi: researchAbi,
  functionName: "newResearcher",
  args: [name],
}).config;  
const {write}  =  useContractWrite(newResearcherconfig);

  return (
    <>
      <Head>
        <title>Login Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Martel+Sans&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <main className="flex flex-col justify-between items-center p-24 min-h-screen">
        <div
          className=
            "display-inherit justify-inherit items-inherit text-xs  w-full z-2  font-mono "
          
        >
          <div className="h-[100%] w-[35%] z-10 top-0 pt-[20px] flex justify-center absolute left-0 bg-[#2F2E41]">
            <div className=" border-red-500">
              <div className="">
                <Link href="/">
                  <p className="text-[20px] ml-4 text-white font-Michroma h-0 mt-2 mb-[25%]">
                    SCHOLAR3
                  </p>
                </Link>
              </div>
              <div>
                <Image
                  className="h-[45em] w-[64em]"
                  height={1000}
                  width={700}
                  style={{ objectFit: "cover", objectPosition: "left" }}
                  src="/textimg.webp"
                ></Image>
              </div>
            </div>
          </div>
          <div className="h-[100%] w-[65%] absolute z-1 top-0 right-0 bg-[#cbcbcb]  border-red-500 ">
            <div className="">
              <div
                className="flex flex-col justify-center text-center max-h-screen "
              >
                <div className=" self-end mt-4 mr-2"><ConnectButton /></div>
                <h2 className="mt-12 font-Inconsolata font-extrabold self-center text-[40px] leading-[50px] pl-5 pb-8">
                  Create Researcher Profile
                </h2>
                <input
                  spellCheck="false"
                  className="w-[310px] h-[34px] self-center font-Inconsolata bg-white rounded-lg border-none outline-none font-medium text-base leading-12 text-center
                    "
                  type="text"
                  placeholder="Username"
                  value={name}
                  onChange={nameChange}

                />
                <br />
                <button className=" bg-[#2F2E41] self-center rounded-lg w-[165px] h-[45px] font-Inconsolata font-semibold text-white text-center text-lg hover:bg-black transition-all "
                onClick={write}>
                  Create Account
                </button>
                <Image
                  className="mt-[14%]  h-[250px] w-[300px] self-center   "
                  src="/undrawPic.png"
                  width={400}
                  height={300}
                ></Image>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
